
name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'

    - name: Set up Android SDK
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y openjdk-8-jdk
        echo y | sdkmanager --licenses
        sdkmanager "build-tools;30.0.3" "platforms;android-30" "platform-tools"

    - name: Build APK
      run: ./gradlew assembleRelease

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: app-release
        path: app/build/outputs/apk/release/app-release.apk
